version: '3.7'

volumes:
  minio0:

services:
  minio0:
    container_name: minio0
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio0:/data
    ports:
      - "9000:9000"
      - "9001:9001"
