name: Lint
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: npm run lint
      - uses: codepunkt/npm-lockfile-changes@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
